## These two functions work together to take a matrix as input, calculate its
## inverse matrix, and then cache this inverse matrix. 

## The first function, makeCacheMatrix(), takes a matrix as its input and  
## returns a list of four functions (set, get, setinv, and getinv).  It also 
## stores the input matrix as "x" and sets "inv" to NULL.

makeCacheMatrix <- function(x = matrix()) {
  inv <- NULL
  set <- function(y) {
    x <<- y
    inv <<- NULL
  }
  get <- function() x
  setinv <- function(z) inv <<- z
  getinv <- function() inv
  list(set = set, get = get, setinv = setinv, getinv = getinv)

}


## cacheSolve() takes the list generated by makeCacheMatrix() as input, then 
## calculates and returns the inverse of the matrix originally inputted into 
## makeCacheMatrix().

## If the makeCacheMatrix() function is assigned to an object, cacheSolve() 
## caches this inverse matrix into the environment of that object. For example,
## for x_list <- makeCacheMatrix(x), cacheSolve(x_list) will cache the
## inverse of matrix "x" as the variable "inv" in x_list's environment. 

## cacheSolve() first checks if the inverse matrix of its input argument has
## already been calculated and cached. If so, it prints a message saying 
## "getting cached data" and returns this inverse. If not, it calculates the
## inverse matrix, caches it, and returns the inverse matrix to the console.

 
cacheSolve <- function(x, ...) {
  inv <- x$getinv()
  if(!is.null(inv)) {
    message("getting cached data")
    return(inv)
  } else {
  inv <- solve(x$get(), ...)
  x$setinv(inv)
  inv
  }
}
